/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CloudPass;

import org.junit.Test;

import CloudPass.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = null;
        assertNull("app is not null", classUnderTest);
    }
}
